export const SAVE_EXPRESSION = 'SAVE_EXPRESSION';

export const DELETE_EXPRESSION = 'DELETE_EXPRESSION';

export const CLEAR_REGISTER = 'CLEAR_REGISTER';

export const EDIT_EXPRESSION = 'EDIT_EXPRESSION';

export const REGISTER_TOKEN = 'REGISTER_TOKEN';

export const FULL_STATE = 'FULL_STATE';
